FROM debian:bullseye

RUN apt -y update && apt -y upgrade
RUN apt -y install mariadb-server \
    nginx \
    mariadb-server \
    php7.3-fpm \
    php7.3-mysql \
    php7.3-mbstring \
    php7.3-xml \
    curl



