version: "3.8"

# Volumes
volumes:
  mariadb:
    name: mariadb
    external: true
  wordpress:
    name: wordpress
    external: true
  static:
    name: static
    external: true

# Networks
networks:
  inception:
    name: inception
    driver: bridge

# Services (Containers)
services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    init: true
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:42
    init: true
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx:42
    init: true
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME
        - CERTS_KEY
        - CERTS_CRT
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - static:/usr/share/nginx/html
    restart: always
    depends_on:
      - mariadb
      - wordpress

##################  BONUS  ##################
  redis:
    container_name: redis
    image: redis:42
    init: true
    build:
      context: ./requirements/bonus/redis-cache
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - mariadb
      - wordpress
      - nginx

  ftp:
    container_name: ftp
    image: ftp:42
    init: true
    build:
      context: ./requirements/bonus/ftp-server
      dockerfile: Dockerfile
      args:
        - FTP_USER
        - FTP_PASSWORD
    networks:
      - inception
    volumes:
      - wordpress:/home/$FTP_USER/ftp
    ports:
      - "20:20"
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always
    depends_on:
      - mariadb
      - wordpress
      - nginx

  static:
    container_name: static
    image: static:42
    init: true
    build:
      context: ./requirements/bonus/static-website
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - static:/usr/src/app
    ports:
      - "3000:3000"
    restart: always